module.exports = {
  LOBBY_CHAT:"LOBBY_CHAT",
  USER_CONENCTED:"USER_CONENCTED",
  MESSAGE_RECIVED:"MESSAGE_RECIVED",
  MESSAGE_SENT:"MESSAGE_SENT",
  USER_DISCONNECTED:"USER_DISCONNECTED",
  TYPING:"TYPING",
  VERIFY_USER:"VERIFY_USER",
  LOGOUT:"LOGOUT"
}
